services:
  postgres:
    image: postgres:18
    shm_size: 128mb
    volumes:
      - 'pg_data:/var/lib/postgresql/18/docker'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: godns

  redis:
    image: redis:8
    command: ["redis-server", "--requirepass", "root"]
    ports:
      - '6379:6379'

volumes:
  pg_data: